name = "url-shortener"
main = ".worker-next/index.mjs"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

minify = true

assets = { directory = ".worker-next/assets", binding = "ASSETS" }

[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "LINKS"
id = "ID"

[[kv_namespaces]]
binding = "REVERSE_LINKS"
id = "ID"

[[kv_namespaces]]
binding = "LIMITS"
id = "ID"

