#:schema node_modules/wrangler/config-schema.json
name = "url-shortener"
main = ".worker-next/index.mjs"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

# Minification helps to keep the Worker bundle size down and improve start up time.
minify = true

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

[[kv_namespaces]]
binding = "LINKS"
id = "a8074402f01c4314abc07f894696ce84"

[[kv_namespaces]]
binding = "REVERSE_LINKS"
id = "24b2ed4580a44a8d9f632cd2d2864e88"

[[kv_namespaces]]
binding = "LIMITS"
id = "dc35f6334c6249e48e217f57d8054c28"

[observability]
enabled = true
head_sampling_rate = 1